// 三國志地圖策略遊戲 - 武將數據庫

export const GENERALS = [
  // ================= 曹操陣營 / 魏國名臣 =================
  { 
    id: 'cao_cao', 
    name: '曹操', 
    stats: { lead: 98, str: 72, int: 92, pol: 94, cha: 96 }, 
    trait: 'falsehood', 
    portrait: 'portraits/cao_cao.jpg', 
    portraitColor: '#0d47a1', 
    description: '字孟德，治世之能臣，亂世之奸雄。魏武帝。', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'cavalry' 
  },
  { 
    id: 'xiahou_dun', 
    name: '夏侯惇', 
    stats: { lead: 89, str: 90, int: 60, pol: 65, cha: 82 }, 
    portrait: 'portraits/xiahou_dun.jpg', 
    portraitColor: '#1976d2', 
    description: '字元讓，魏國元勳大將，曾拔矢啖睛，作戰勇猛。', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'cavalry' 
  },
  { 
    id: 'xiahou_yuan', 
    name: '夏侯淵', 
    stats: { lead: 87, str: 91, int: 55, pol: 61, cha: 78 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1976d2', 
    description: '字妙才，擅長千里奔襲，虎步關右。', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'archer' 
  },
  { 
    id: 'cao_ren', 
    name: '曹仁', 
    stats: { lead: 89, str: 86, int: 62, pol: 56, cha: 76 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1565c0', 
    description: '字子孝，曹魏天人將軍，守城之能天下第一。', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'infantry' 
  },
  { 
    id: 'cao_hong', 
    name: '曹洪', 
    stats: { lead: 79, str: 81, int: 44, pol: 45, cha: 62 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1565c0', 
    description: '字子廉，捨命救曹操，「天下可無洪，不可無公」。', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'cavalry' 
  },
  { 
    id: 'guo_jia', 
    name: '郭嘉', 
    stats: { lead: 51, str: 15, int: 98, pol: 84, cha: 78 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/guo_jia.jpg', 
    portraitColor: '#42a5f5', 
    description: '字奉孝，才策謀略，世之奇士，算無遺策。', 
    appearanceYear: 196, 
    appearanceCity: 'xuchang', 
    unitType: 'archer' 
  },
  { 
    id: 'xun_yu', 
    name: '荀彧', 
    stats: { lead: 32, str: 14, int: 95, pol: 99, cha: 85 }, 
    trait: 'wealthy', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#64b5f6', 
    description: '字文若，王佐之才，曹操統一北方的首席謀臣。', 
    appearanceYear: 189, 
    appearanceCity: 'xuchang', 
    unitType: 'infantry' 
  },
  { 
    id: 'xun_you', 
    name: '荀攸', 
    stats: { lead: 73, str: 24, int: 94, pol: 88, cha: 80 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#64b5f6', 
    description: '字公達，曹操謀主，算無遺策，深密有智防。', 
    appearanceYear: 196, 
    appearanceCity: 'xuchang', 
    unitType: 'archer' 
  },
  { 
    id: 'jia_xu', 
    name: '賈詡', 
    stats: { lead: 86, str: 48, int: 97, pol: 85, cha: 57 }, 
    trait: 'falsehood', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#283593', 
    description: '字文和，人稱「毒士」，算無遺策，自保之道天下無雙。', 
    appearanceYear: 190, 
    appearanceCity: 'changan', 
    unitType: 'archer' 
  },
  { 
    id: 'cheng_yu', 
    name: '程昱', 
    stats: { lead: 70, str: 49, int: 90, pol: 79, cha: 55 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1e88e5', 
    description: '字仲德，曹操核心謀臣，性格剛戾，長於謀略。', 
    appearanceYear: 192, 
    appearanceCity: 'xuchang', 
    unitType: 'infantry' 
  },
  { 
    id: 'xu_chu', 
    name: '許褚', 
    stats: { lead: 65, str: 96, int: 36, pol: 20, cha: 56 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ff8f00', 
    description: '字仲康，人稱「虎癡」，曹操貼身護衛，勇力絕倫。', 
    appearanceYear: 196, 
    appearanceCity: 'xuchang', 
    unitType: 'infantry' 
  },
  { 
    id: 'dian_wei', 
    name: '典韋', 
    stats: { lead: 68, str: 95, int: 35, pol: 20, cha: 58 }, 
    trait: 'god_of_war', 
    portrait: 'portraits/dian_wei.jpg', 
    portraitColor: '#d84315', 
    description: '古之惡來，力大無窮，於宛城捨身救主。', 
    appearanceYear: 190, 
    appearanceCity: 'runan', 
    unitType: 'infantry' 
  },
  { 
    id: 'zhang_he', 
    name: '張郃', 
    stats: { lead: 89, str: 89, int: 74, pol: 57, cha: 71 }, 
    trait: 'flying_gen', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1565c0', 
    description: '字儁乂，魏國五子良將，巧變善戰，街亭破馬謖。', 
    appearanceYear: 190, 
    appearanceCity: 'ye', 
    unitType: 'cavalry' 
  },
  { 
    id: 'xu_huang', 
    name: '徐晃', 
    stats: { lead: 88, str: 90, int: 74, pol: 48, cha: 71 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1565c0', 
    description: '字公明，魏國五子良將，有周亞夫之風，樊城解圍。', 
    appearanceYear: 194, 
    appearanceCity: 'luoyang', 
    unitType: 'infantry' 
  },
  { 
    id: 'yu_jin', 
    name: '于禁', 
    stats: { lead: 84, str: 78, int: 72, pol: 55, cha: 58 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1565c0', 
    description: '字文則，魏國五子良將，持軍嚴整，毅重善戰。', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'infantry' 
  },
  { 
    id: 'yue_jin', 
    name: '樂進', 
    stats: { lead: 80, str: 84, int: 53, pol: 51, cha: 60 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1565c0', 
    description: '字文謙，魏國五子良將，每戰先登，勇猛無前。', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'infantry' 
  },
  { 
    id: 'deng_ai', 
    name: '鄧艾', 
    stats: { lead: 94, str: 87, int: 89, pol: 81, cha: 70 }, 
    trait: 'flying_gen', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#0d47a1', 
    description: '字士載，文武兼備，偷渡陰平，一舉滅蜀名將。', 
    appearanceYear: 215, 
    appearanceCity: 'runan', 
    unitType: 'cavalry' 
  },
  { 
    id: 'zhong_hui', 
    name: '鍾會', 
    stats: { lead: 82, str: 51, int: 91, pol: 79, cha: 68 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1976d2', 
    description: '字士季，精練策數，伐蜀主帥之一。', 
    appearanceYear: 220, 
    appearanceCity: 'luoyang', 
    unitType: 'archer' 
  },

  // ================= 劉備陣營 / 蜀漢英豪 =================
  { 
    id: 'liu_bei', 
    name: '劉備', 
    stats: { lead: 80, str: 75, int: 78, pol: 80, cha: 99 }, 
    portrait: 'portraits/liu_bei.jpg', 
    portraitColor: '#1b5e20', 
    description: '字玄德，蜀漢昭烈帝，以仁德布於天下，百折不撓。', 
    appearanceYear: 184, 
    appearanceCity: 'beiping', 
    unitType: 'infantry' 
  },
  { 
    id: 'guan_yu', 
    name: '關羽', 
    stats: { lead: 95, str: 97, int: 75, pol: 62, cha: 93 }, 
    trait: 'god_of_war', 
    portrait: 'portraits/guan_yu.jpg', 
    portraitColor: '#2e7d32', 
    description: '字雲長，威震華夏，萬人敵，忠義千秋武聖。', 
    appearanceYear: 184, 
    appearanceCity: 'beiping', 
    unitType: 'infantry' 
  },
  { 
    id: 'zhang_fei', 
    name: '張飛', 
    stats: { lead: 85, str: 98, int: 30, pol: 18, cha: 45 }, 
    trait: 'flying_gen', 
    portrait: 'portraits/zhang_fei.jpg', 
    portraitColor: '#4caf50', 
    description: '字翼德，勇冠三軍，當陽橋一聲喝退曹操百萬大軍。', 
    appearanceYear: 184, 
    appearanceCity: 'beiping', 
    unitType: 'cavalry' 
  },
  { 
    id: 'zhao_yun', 
    name: '趙雲', 
    stats: { lead: 92, str: 96, int: 76, pol: 65, cha: 91 }, 
    trait: 'god_of_war', 
    portrait: 'portraits/zhao_yun.jpg', 
    portraitColor: '#81c784', 
    description: '字子龍，一身是膽，長坂坡七進七出救阿斗。', 
    appearanceYear: 191, 
    appearanceCity: 'beiping', 
    unitType: 'cavalry' 
  },
  { 
    id: 'zhuge_liang', 
    name: '諸葛亮', 
    stats: { lead: 98, str: 38, int: 100, pol: 98, cha: 95 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/zhuge_liang.jpg', 
    portraitColor: '#00838f', 
    description: '字孔明，臥龍先生，智冠天下，鞠躬盡瘁死而後已。', 
    appearanceYear: 207, 
    appearanceCity: 'xiangyang', 
    unitType: 'archer' 
  },
  { 
    id: 'pang_tong', 
    name: '龐統', 
    stats: { lead: 80, str: 34, int: 97, pol: 85, cha: 69 }, 
    portrait: 'portraits/pang_tong.jpg', 
    portraitColor: '#00695c', 
    description: '字士元，號鳳雛，與諸葛亮齊名，助劉備奪取益州。', 
    appearanceYear: 208, 
    appearanceCity: 'xiangyang', 
    unitType: 'archer' 
  },
  { 
    id: 'fa_zheng', 
    name: '法正', 
    stats: { lead: 82, str: 47, int: 94, pol: 78, cha: 52 }, 
    trait: 'falsehood', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#388e3c', 
    description: '字孝直，蜀漢謀主，奇策算計助定軍山斬夏侯淵。', 
    appearanceYear: 200, 
    appearanceCity: 'chengdu', 
    unitType: 'archer' 
  },
  { 
    id: 'xu_shu', 
    name: '徐庶', 
    stats: { lead: 81, str: 64, int: 93, pol: 82, cha: 81 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#2e7d32', 
    description: '字元直，早期為劉備破曹仁八門金鎖陣，身在曹營心在漢。', 
    appearanceYear: 200, 
    appearanceCity: 'xiangyang', 
    unitType: 'infantry' 
  },
  { 
    id: 'jiang_wei', 
    name: '姜維', 
    stats: { lead: 90, str: 89, int: 90, pol: 67, cha: 80 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#1b5e20', 
    description: '字伯約，文武雙全，幼麟繼承武侯遺志，九伐中原。', 
    appearanceYear: 220, 
    appearanceCity: 'tianshui', 
    unitType: 'cavalry' 
  },
  { 
    id: 'wei_yan', 
    name: '魏延', 
    stats: { lead: 85, str: 92, int: 69, pol: 46, cha: 39 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e65100', 
    description: '字文長，蜀漢名將，鎮守漢中十載，勇烈過人。', 
    appearanceYear: 196, 
    appearanceCity: 'changsha', 
    unitType: 'infantry' 
  },
  { 
    id: 'huang_zhong', 
    name: '黃忠', 
    stats: { lead: 86, str: 93, int: 60, pol: 52, cha: 75 }, 
    portrait: 'portraits/huang_zhong.jpg', 
    portraitColor: '#e65100', 
    description: '字漢升，五虎上將，老當益壯，百步穿楊，斬夏侯淵。', 
    appearanceYear: 190, 
    appearanceCity: 'changsha', 
    unitType: 'archer' 
  },
  { 
    id: 'ma_chao', 
    name: '馬超', 
    stats: { lead: 88, str: 96, int: 44, pol: 26, cha: 82 }, 
    trait: 'god_of_war', 
    portrait: 'portraits/ma_chao.jpg', 
    portraitColor: '#e0a800', 
    description: '字孟起，錦馬超，西涼威震天下，潼關逼曹操割鬚棄袍。', 
    appearanceYear: 196, 
    appearanceCity: 'tianshui', 
    unitType: 'cavalry' 
  },
  { 
    id: 'ma_dai', 
    name: '馬岱', 
    stats: { lead: 78, str: 82, int: 61, pol: 51, cha: 68 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#4caf50', 
    description: '馬超從弟，忠勇敏銳，奉武侯密令斬魏延。', 
    appearanceYear: 196, 
    appearanceCity: 'tianshui', 
    unitType: 'cavalry' 
  },
  { 
    id: 'guan_ping', 
    name: '關平', 
    stats: { lead: 82, str: 83, int: 72, pol: 60, cha: 77 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#388e3c', 
    description: '關羽長子，勇毅純孝，隨父征戰荊襄，威震江漢。', 
    appearanceYear: 200, 
    appearanceCity: 'xiangyang', 
    unitType: 'infantry' 
  },
  { 
    id: 'guan_xing', 
    name: '關興', 
    stats: { lead: 76, str: 86, int: 68, pol: 57, cha: 74 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#388e3c', 
    description: '關羽次子，陣斬潘璋奪回青龍刀，武侯伐魏先鋒。', 
    appearanceYear: 215, 
    appearanceCity: 'chengdu', 
    unitType: 'cavalry' 
  },
  { 
    id: 'zhang_bao_shu', 
    name: '張苞', 
    stats: { lead: 77, str: 87, int: 48, pol: 45, cha: 69 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#4caf50', 
    description: '張飛長子，虎父無犬子，英勇善戰，與關興結為兄弟。', 
    appearanceYear: 215, 
    appearanceCity: 'chengdu', 
    unitType: 'cavalry' 
  },
  { 
    id: 'mi_zhu', 
    name: '糜竺', 
    stats: { lead: 34, str: 28, int: 73, pol: 80, cha: 84 }, 
    trait: 'wealthy', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#81c784', 
    description: '字子仲，徐州巨富，傾家財資助劉備起兵，忠義敦厚。', 
    appearanceYear: 190, 
    appearanceCity: 'xuchang', 
    unitType: 'infantry' 
  },
  { 
    id: 'meng_huo', 
    name: '孟獲', 
    stats: { lead: 76, str: 87, int: 42, pol: 18, cha: 79 }, 
    portrait: 'portraits/meng_huo.jpg', 
    portraitColor: '#558b2f', 
    description: '南蠻蠻王，作戰勇悍，被諸葛亮七擒七縱後心悅誠服。', 
    appearanceYear: 215, 
    appearanceCity: 'yunnan', 
    unitType: 'infantry' 
  },
  { 
    id: 'zhu_rong', 
    name: '祝融夫人', 
    stats: { lead: 74, str: 85, int: 53, pol: 25, cha: 78 }, 
    trait: 'beauty', 
    portrait: 'portraits/zhu_rong.jpg', 
    portraitColor: '#e91e63', 
    description: '相傳為火神祝融後裔，孟獲之妻，飛刀絕技百發百中。', 
    appearanceYear: 215, 
    appearanceCity: 'yunnan', 
    unitType: 'cavalry' 
  },
  { 
    id: 'wei_wen', 
    name: '衛溫', 
    stats: { lead: 75, str: 72, int: 70, pol: 68, cha: 74 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#26a69a', 
    description: '東吳航海將軍，奉孫權之命率甲士萬人浮海遠征，發現並經略夷州（台灣）。', 
    appearanceYear: 215, 
    appearanceCity: 'yizhou', 
    unitType: 'archer' 
  },
  { 
    id: 'gongsun_du', 
    name: '公孫度', 
    stats: { lead: 78, str: 75, int: 72, pol: 76, cha: 70 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#78909c', 
    description: '字升濟，自號遼東侯，東伐高句麗，西擊烏桓，雄霸遼東數十年。', 
    appearanceYear: 184, 
    appearanceCity: 'liaodong', 
    unitType: 'cavalry' 
  },
  { 
    id: 'shi_xie', 
    name: '士燮', 
    stats: { lead: 65, str: 55, int: 82, pol: 88, cha: 86 }, 
    trait: 'wealthy', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#8d6e63', 
    description: '字威彥，交趾太守，嶺南名儒，保境安民數十年，使嶺南成為海外商貿樂土。', 
    appearanceYear: 184, 
    appearanceCity: 'jiaozhi', 
    unitType: 'infantry' 
  },

  // ================= 孫權陣營 / 東吳群英 =================
  { 
    id: 'sun_quan', 
    name: '孫權', 
    stats: { lead: 76, str: 70, int: 80, pol: 88, cha: 90 }, 
    portrait: 'portraits/sun_quan.jpg', 
    portraitColor: '#b71c1c', 
    description: '字仲謀，吳大帝，生子當如孫仲謀，割據江東開創東吳。', 
    appearanceYear: 196, 
    appearanceCity: 'jianye', 
    unitType: 'archer' 
  },
  { 
    id: 'sun_jian', 
    name: '孫堅', 
    stats: { lead: 93, str: 90, int: 74, pol: 73, cha: 89 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#b71c1c', 
    description: '字文臺，江東之虎，斬華雄破洛陽，勇烈無比。', 
    appearanceYear: 184, 
    appearanceCity: 'jianye', 
    unitType: 'infantry' 
  },
  { 
    id: 'sun_ce', 
    name: '孫策', 
    stats: { lead: 92, str: 92, int: 69, pol: 70, cha: 92 }, 
    portrait: 'portraits/sun_ce.jpg', 
    portraitColor: '#b71c1c', 
    description: '字伯符，江東小霸王，數年間平定江東六郡，英氣傑濟。', 
    appearanceYear: 194, 
    appearanceCity: 'jianye', 
    unitType: 'cavalry' 
  },
  { 
    id: 'zhou_yu', 
    name: '周瑜', 
    stats: { lead: 97, str: 71, int: 96, pol: 86, cha: 93 }, 
    trait: 'falsehood', 
    portrait: 'portraits/zhou_yu.jpg', 
    portraitColor: '#d32f2f', 
    description: '字公瑾，美周郎，羽扇綸巾，赤壁之戰火燒百萬曹軍。', 
    appearanceYear: 190, 
    appearanceCity: 'jianye', 
    unitType: 'archer' 
  },
  { 
    id: 'lu_su', 
    name: '魯肅', 
    stats: { lead: 80, str: 56, int: 92, pol: 92, cha: 89 }, 
    trait: 'wealthy', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e57373', 
    description: '字子敬，榻上策定天下三分，忠厚大度，極富戰略眼光。', 
    appearanceYear: 196, 
    appearanceCity: 'jianye', 
    unitType: 'archer' 
  },
  { 
    id: 'lu_meng', 
    name: '呂蒙', 
    stats: { lead: 91, str: 81, int: 89, pol: 78, cha: 82 }, 
    trait: 'wealthy', 
    portrait: 'portraits/lu_meng.jpg', 
    portraitColor: '#ef5350', 
    description: '字子明，吳下阿蒙刮目相看，白衣渡江奇襲荊州。', 
    appearanceYear: 198, 
    appearanceCity: 'huiji', 
    unitType: 'infantry' 
  },
  { 
    id: 'lu_xun', 
    name: '陸遜', 
    stats: { lead: 96, str: 69, int: 95, pol: 87, cha: 90 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/lu_xun.jpg', 
    portraitColor: '#c62828', 
    description: '字伯言，東吳大都督，夷陵火燒連營七百里大破劉備。', 
    appearanceYear: 205, 
    appearanceCity: 'huiji', 
    unitType: 'archer' 
  },
  { 
    id: 'gan_ning', 
    name: '甘寧', 
    stats: { lead: 86, str: 94, int: 62, pol: 45, cha: 70 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e57373', 
    description: '字興霸，錦帆賊，百騎劫魏營，曹操嘆「孟德有張遼，孤有甘興霸」。', 
    appearanceYear: 194, 
    appearanceCity: 'changsha', 
    unitType: 'infantry' 
  },
  { 
    id: 'taishi_ci', 
    name: '太史慈', 
    stats: { lead: 82, str: 93, int: 66, pol: 58, cha: 79 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e57373', 
    description: '字子義，神亭嶺酣戰孫策，弦不虛發，篤烈信義。', 
    appearanceYear: 190, 
    appearanceCity: 'jianye', 
    unitType: 'archer' 
  },
  { 
    id: 'huang_gai', 
    name: '黃蓋', 
    stats: { lead: 83, str: 81, int: 70, pol: 65, cha: 82 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#d32f2f', 
    description: '字公覆，東吳老臣，苦肉計火燒赤壁首功之將。', 
    appearanceYear: 184, 
    appearanceCity: 'jianye', 
    unitType: 'infantry' 
  },
  { 
    id: 'cheng_pu', 
    name: '程普', 
    stats: { lead: 84, str: 79, int: 75, pol: 72, cha: 83 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#d32f2f', 
    description: '字德謀，東吳三代元老，軍中尊稱「程公」。', 
    appearanceYear: 184, 
    appearanceCity: 'jianye', 
    unitType: 'infantry' 
  },
  { 
    id: 'zhou_tai', 
    name: '周泰', 
    stats: { lead: 77, str: 91, int: 48, pol: 38, cha: 63 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e57373', 
    description: '字幼平，勇猛無畏，身受數十處重傷死戰護孫權。', 
    appearanceYear: 194, 
    appearanceCity: 'huiji', 
    unitType: 'infantry' 
  },
  { 
    id: 'ling_tong', 
    name: '凌統', 
    stats: { lead: 77, str: 89, int: 60, pol: 40, cha: 71 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e57373', 
    description: '字公績，江表虎臣，國士之風，與甘寧盡釋前嫌。', 
    appearanceYear: 200, 
    appearanceCity: 'jianye', 
    unitType: 'infantry' 
  },
  { 
    id: 'zhang_zhao', 
    name: '張昭', 
    stats: { lead: 31, str: 24, int: 84, pol: 97, cha: 80 }, 
    trait: 'wealthy', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ff8a80', 
    description: '字子布，江東文臣之首，孫策託孤「內事不決問張昭」。', 
    appearanceYear: 194, 
    appearanceCity: 'jianye', 
    unitType: 'infantry' 
  },
  { 
    id: 'da_qiao', 
    name: '大喬', 
    stats: { lead: 16, str: 11, int: 75, pol: 72, cha: 96 }, 
    trait: 'beauty', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#f48fb1', 
    description: '江東二喬之大喬，孫策之妻，沉魚落雁，絕代佳人。', 
    appearanceYear: 196, 
    appearanceCity: 'jianye', 
    unitType: 'archer' 
  },
  { 
    id: 'xiao_qiao', 
    name: '小喬', 
    stats: { lead: 15, str: 12, int: 77, pol: 70, cha: 95 }, 
    trait: 'beauty', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#f48fb1', 
    description: '江東二喬之小喬，周瑜之妻，國色天香，傾國傾城。', 
    appearanceYear: 196, 
    appearanceCity: 'jianye', 
    unitType: 'archer' 
  },
  { 
    id: 'sun_shangxiang', 
    name: '孫尚香', 
    stats: { lead: 75, str: 86, int: 68, pol: 60, cha: 88 }, 
    trait: 'beauty', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e91e63', 
    description: '孫權之妹，人稱「弓腰姬」，剛勇果烈，巾幗不讓鬚眉。', 
    appearanceYear: 200, 
    appearanceCity: 'jianye', 
    unitType: 'archer' 
  },

  // ================= 董卓 / 呂布陣營 =================
  { 
    id: 'dong_zhuo', 
    name: '董卓', 
    stats: { lead: 74, str: 86, int: 55, pol: 40, cha: 35 }, 
    portrait: 'portraits/dong_zhuo.jpg', 
    portraitColor: '#4a148c', 
    description: '字仲穎，西涼霸主，廢帝弒太后，性情暴虐，權傾朝野。', 
    appearanceYear: 184, 
    appearanceCity: 'changan', 
    unitType: 'cavalry' 
  },
  { 
    id: 'lu_bu', 
    name: '呂布', 
    stats: { lead: 90, str: 100, int: 26, pol: 13, cha: 40 }, 
    trait: 'flying_gen', 
    portrait: 'portraits/lu_bu.jpg', 
    portraitColor: '#7b1fa2', 
    description: '字奉先，三國第一猛將，人中呂布馬中赤兔，天下無雙。', 
    appearanceYear: 184, 
    appearanceCity: 'changan', 
    unitType: 'cavalry' 
  },
  { 
    id: 'zhang_liao', 
    name: '張遼', 
    stats: { lead: 93, str: 92, int: 78, pol: 58, cha: 78 }, 
    trait: 'flying_gen', 
    portrait: 'portraits/zhang_liao.jpg', 
    portraitColor: '#ab47bc', 
    description: '字文遠，威震逍遙津，八百破十萬，江東小兒不敢夜啼。', 
    appearanceYear: 189, 
    appearanceCity: 'tianshui', 
    unitType: 'cavalry' 
  },
  { 
    id: 'gao_shun', 
    name: '高順', 
    stats: { lead: 86, str: 86, int: 56, pol: 46, cha: 73 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#6a1b9a', 
    description: '呂布帳下陷陣營統帥，治軍嚴明，攻無不克，忠勇死節。', 
    appearanceYear: 189, 
    appearanceCity: 'luoyang', 
    unitType: 'infantry' 
  },
  { 
    id: 'chen_gong', 
    name: '陳宮', 
    stats: { lead: 78, str: 55, int: 89, pol: 83, cha: 67 }, 
    trait: 'falsehood', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#8e24aa', 
    description: '字公臺，剛直烈性，足智多謀，為呂布首席謀士。', 
    appearanceYear: 189, 
    appearanceCity: 'xuchang', 
    unitType: 'archer' 
  },
  { 
    id: 'li_ru', 
    name: '李儒', 
    stats: { lead: 45, str: 20, int: 93, pol: 80, cha: 25 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ba68c8', 
    description: '董卓心腹謀士，陰狠毒辣，助董卓把持朝政。', 
    appearanceYear: 184, 
    appearanceCity: 'changan', 
    unitType: 'archer' 
  },
  { 
    id: 'hua_xiong', 
    name: '華雄', 
    stats: { lead: 72, str: 92, int: 42, pol: 39, cha: 50 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ab47bc', 
    description: '西涼猛將，汜水關連斬聯軍數將，後為關羽溫酒所斬。', 
    appearanceYear: 184, 
    appearanceCity: 'luoyang', 
    unitType: 'cavalry' 
  },
  { 
    id: 'diao_chan', 
    name: '貂蟬', 
    stats: { lead: 20, str: 26, int: 81, pol: 65, cha: 100 }, 
    trait: 'beauty', 
    portrait: 'portraits/diao_chan.jpg', 
    portraitColor: '#f06292', 
    description: '三國第一美女，閉月羞花，以連環計除滅暴董。', 
    appearanceYear: 191, 
    appearanceCity: 'changan', 
    unitType: 'archer' 
  },

  // ================= 袁紹陣營 / 河北群雄 =================
  { 
    id: 'yuan_shao', 
    name: '袁紹', 
    stats: { lead: 82, str: 69, int: 70, pol: 72, cha: 85 }, 
    portrait: 'portraits/yuan_shao.jpg', 
    portraitColor: '#fbc02d', 
    description: '字本初，四世三公，關東聯軍盟主，統一河北四州。', 
    appearanceYear: 184, 
    appearanceCity: 'ye', 
    unitType: 'infantry' 
  },
  { 
    id: 'yan_liang', 
    name: '顏良', 
    stats: { lead: 83, str: 93, int: 40, pol: 30, cha: 50 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#fdd835', 
    description: '河北四庭柱之首，勇冠三軍，白馬之戰折戟。', 
    appearanceYear: 189, 
    appearanceCity: 'ye', 
    unitType: 'cavalry' 
  },
  { 
    id: 'wen_chou', 
    name: '文醜', 
    stats: { lead: 82, str: 92, int: 38, pol: 25, cha: 45 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ffee58', 
    description: '河北名將，與顏良齊名，驍勇善戰。', 
    appearanceYear: 189, 
    appearanceCity: 'ye', 
    unitType: 'cavalry' 
  },
  { 
    id: 'tian_feng', 
    name: '田豐', 
    stats: { lead: 60, str: 29, int: 93, pol: 87, cha: 65 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#fbc02d', 
    description: '字元皓，袁紹頂尖謀臣，剛直犯上，深諳用兵權謀。', 
    appearanceYear: 189, 
    appearanceCity: 'ye', 
    unitType: 'archer' 
  },
  { 
    id: 'ju_shou', 
    name: '沮授', 
    stats: { lead: 76, str: 35, int: 90, pol: 84, cha: 72 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#fbc02d', 
    description: '袁紹監軍謀臣，少有大志，多謀略，威重明略。', 
    appearanceYear: 189, 
    appearanceCity: 'ye', 
    unitType: 'archer' 
  },
  { 
    id: 'shen_pei', 
    name: '審配', 
    stats: { lead: 78, str: 60, int: 83, pol: 75, cha: 66 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#fbc02d', 
    description: '字正南，性烈忠讜，誓死堅守鄴城，忠勇死節。', 
    appearanceYear: 189, 
    appearanceCity: 'ye', 
    unitType: 'infantry' 
  },

  // ================= 黃巾 / 袁術 / 馬騰 / 地方諸侯 =================
  { 
    id: 'zhang_jiao', 
    name: '張角', 
    stats: { lead: 86, str: 25, int: 86, pol: 80, cha: 98 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ffb300', 
    description: '天公將軍，太平道大賢良師，發動百萬黃巾之亂。', 
    appearanceYear: 184, 
    appearanceCity: 'ye', 
    unitType: 'archer' 
  },
  { 
    id: 'zhang_bao', 
    name: '張寶', 
    stats: { lead: 79, str: 71, int: 81, pol: 65, cha: 82 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ffca28', 
    description: '地公將軍，張角二弟，善用妖術符水。', 
    appearanceYear: 184, 
    appearanceCity: 'runan', 
    unitType: 'infantry' 
  },
  { 
    id: 'zhang_liang', 
    name: '張梁', 
    stats: { lead: 78, str: 80, int: 68, pol: 55, cha: 79 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ffca28', 
    description: '人公將軍，張角三弟，率黃巾主力死守曲陽。', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'infantry' 
  },
  { 
    id: 'yuan_shu', 
    name: '袁術', 
    stats: { lead: 65, str: 65, int: 61, pol: 73, cha: 78 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#f48fb1', 
    description: '字公路，四世三公，後得傳國玉璽於壽春僭越稱帝。', 
    appearanceYear: 184, 
    appearanceCity: 'runan', 
    unitType: 'infantry' 
  },
  { 
    id: 'ji_ling', 
    name: '紀靈', 
    stats: { lead: 78, str: 83, int: 51, pol: 48, cha: 60 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#f48fb1', 
    description: '袁術帳下第一猛將，使五十斤三尖刀，大戰關羽三十合。', 
    appearanceYear: 190, 
    appearanceCity: 'runan', 
    unitType: 'cavalry' 
  },
  { 
    id: 'ma_teng', 
    name: '馬騰', 
    stats: { lead: 80, str: 84, int: 53, pol: 66, cha: 82 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#8d6e63', 
    description: '字壽成，西涼名宿，伏波將軍馬援後裔，忠於漢室。', 
    appearanceYear: 184, 
    appearanceCity: 'tianshui', 
    unitType: 'cavalry' 
  },
  { 
    id: 'pang_de', 
    name: '龐德', 
    stats: { lead: 80, str: 94, int: 68, pol: 44, cha: 70 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#8d6e63', 
    description: '字令明，西涼勇將，抬棺戰關羽，射中關羽前額。', 
    appearanceYear: 196, 
    appearanceCity: 'tianshui', 
    unitType: 'cavalry' 
  },
  { 
    id: 'gongsun_zan', 
    name: '公孫瓚', 
    stats: { lead: 84, str: 83, int: 61, pol: 58, cha: 74 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#9e9e9e', 
    description: '字伯珪，白馬將軍，率「白馬義從」威震塞外烏桓。', 
    appearanceYear: 184, 
    appearanceCity: 'beiping', 
    unitType: 'cavalry' 
  },
  { 
    id: 'liu_biao', 
    name: '劉表', 
    stats: { lead: 60, str: 31, int: 71, pol: 81, cha: 76 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#00acc1', 
    description: '字景升，八俊之一，單騎入荊州，保境安民愛賢好士。', 
    appearanceYear: 184, 
    appearanceCity: 'xiangyang', 
    unitType: 'infantry' 
  },
  { 
    id: 'wen_ping', 
    name: '文聘', 
    stats: { lead: 82, str: 82, int: 65, pol: 66, cha: 71 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#00acc1', 
    description: '字仲業，荊楚名將，鎮守江夏數十年，魏之屏障。', 
    appearanceYear: 190, 
    appearanceCity: 'xiangyang', 
    unitType: 'infantry' 
  },
  { 
    id: 'huang_zu', 
    name: '黃祖', 
    stats: { lead: 70, str: 65, int: 55, pol: 50, cha: 45 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#00acc1', 
    description: '江夏太守，多次擊退孫氏進犯，曾射殺孫堅。', 
    appearanceYear: 190, 
    appearanceCity: 'xiangyang', 
    unitType: 'archer' 
  },
  { 
    id: 'liu_zhang', 
    name: '劉璋', 
    stats: { lead: 50, str: 42, int: 52, pol: 65, cha: 68 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#689f38', 
    description: '字季玉，益州牧，性寬仁暗弱，後讓益州於劉備。', 
    appearanceYear: 190, 
    appearanceCity: 'chengdu', 
    unitType: 'infantry' 
  },
  { 
    id: 'zhang_ren', 
    name: '張任', 
    stats: { lead: 84, str: 84, int: 76, pol: 58, cha: 75 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#689f38', 
    description: '益州第一名將，落鳳坡伏擊射殺龐統，死節不降。', 
    appearanceYear: 190, 
    appearanceCity: 'chengdu', 
    unitType: 'archer' 
  },
  { 
    id: 'yan_yan', 
    name: '嚴顏', 
    stats: { lead: 82, str: 83, int: 67, pol: 62, cha: 75 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#689f38', 
    description: '巴郡太守，「蜀中只有斷頭將軍，無降將軍」，為張飛義釋。', 
    appearanceYear: 190, 
    appearanceCity: 'chengdu', 
    unitType: 'archer' 
  },

  // ================= 奇人名士 / 在野高人 =================
  { 
    id: 'sima_yi', 
    name: '司馬懿', 
    stats: { lead: 98, str: 63, int: 99, pol: 93, cha: 87 }, 
    trait: 'falsehood', 
    portrait: 'portraits/sima_yi.jpg', 
    portraitColor: '#37474f', 
    description: '字仲達，狼顧之相，深謀遠慮，三國終結者。', 
    appearanceYear: 200, 
    appearanceCity: 'luoyang', 
    unitType: 'infantry' 
  },
  { 
    id: 'hua_tuo', 
    name: '華佗', 
    stats: { lead: 10, str: 15, int: 90, pol: 50, cha: 85 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#81c784', 
    description: '字元化，東漢神醫，精通外科，發明麻沸散與五禽戲。', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'infantry' 
  },
  { 
    id: 'zuo_ci', 
    name: '左慈', 
    stats: { lead: 10, str: 20, int: 96, pol: 60, cha: 90 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#7e57c2', 
    description: '字元放，峨眉山修道方士，通曉奇門遁甲，戲弄曹操。', 
    appearanceYear: 184, 
    appearanceCity: 'chengdu', 
    unitType: 'archer' 
  },
  { 
    id: 'sima_hui', 
    name: '司馬徽', 
    stats: { lead: 20, str: 15, int: 92, pol: 86, cha: 94 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#26a69a', 
    description: '字德操，人稱「水鏡先生」，精通識人之術，推薦臥龍鳳雛。', 
    appearanceYear: 190, 
    appearanceCity: 'xiangyang', 
    unitType: 'infantry' 
  },
  { 
    id: 'cai_wenji', 
    name: '蔡文姬', 
    stats: { lead: 18, str: 15, int: 85, pol: 82, cha: 92 }, 
    trait: 'beauty', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ab47bc', 
    description: '蔡邕之女，博學有才辯，精通音律，作《胡笳十八拍》。', 
    appearanceYear: 190, 
    appearanceCity: 'luoyang', 
    unitType: 'archer' 
  }
,
  // ================= 異域神國與塞外雄主 =================
  { 
    id: 'himiko', 
    name: '卑彌呼', 
    stats: { lead: 85, str: 50, int: 95, pol: 90, cha: 99 }, 
    trait: 'sorcery', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e91e63', 
    description: '東瀛邪馬台國女王，通鬼道惑眾，受魏帝曹叡冊封為「親魏倭王」，賜金印紫綬。', 
    appearanceYear: 184, 
    appearanceCity: 'yamatai', 
    unitType: 'archer' 
  },
  { 
    id: 'nashime', 
    name: '難升米', 
    stats: { lead: 80, str: 78, int: 84, pol: 86, cha: 82 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ad1457', 
    description: '邪馬台國正使兼大夫，奉女王之命出使曹魏，受封「率善中郎將」。', 
    appearanceYear: 184, 
    appearanceCity: 'yamatai', 
    unitType: 'infantry' 
  },
  { 
    id: 'huchuquan', 
    name: '呼廚泉', 
    stats: { lead: 82, str: 86, int: 60, pol: 65, cha: 78 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#5d4037', 
    description: '匈奴單于，羌渠單于之子，統領漠北控弦鐵騎，威震塞外。', 
    appearanceYear: 184, 
    appearanceCity: 'xiongnu', 
    unitType: 'cavalry' 
  },
  { 
    id: 'liu_bao', 
    name: '劉豹', 
    stats: { lead: 80, str: 84, int: 70, pol: 68, cha: 76 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#4e342e', 
    description: '匈奴左賢王，於夫羅之子，漢趙皇帝劉淵之父。', 
    appearanceYear: 190, 
    appearanceCity: 'xiongnu', 
    unitType: 'cavalry' 
  },
  { 
    id: 'tadun', 
    name: '蹋頓', 
    stats: { lead: 84, str: 90, int: 62, pol: 58, cha: 80 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#6d4c41', 
    description: '烏桓單于，驍勇善戰，人稱「總攬三郡，雄視幽冀」，白狼山大戰張遼。', 
    appearanceYear: 184, 
    appearanceCity: 'wuhuan', 
    unitType: 'cavalry' 
  },
  { 
    id: 'midang', 
    name: '迷當大王', 
    stats: { lead: 84, str: 88, int: 65, pol: 60, cha: 82 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#00897b', 
    description: '西羌國王，率鐵車重甲飛斧兵五萬助蜀伐魏，勇猛無比。', 
    appearanceYear: 184, 
    appearanceCity: 'xiqiang', 
    unitType: 'cavalry' 
  },
  { 
    id: 'ehe_shaoge', 
    name: '俄何燒戈', 
    stats: { lead: 78, str: 89, int: 50, pol: 40, cha: 70 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#00695c', 
    description: '西羌先鋒大將，使一柄沉重金背大刀，勇冠三軍。', 
    appearanceYear: 184, 
    appearanceCity: 'xiqiang', 
    unitType: 'cavalry' 
  },
  { 
    id: 'mulu', 
    name: '木鹿大王', 
    stats: { lead: 82, str: 85, int: 80, pol: 50, cha: 84 }, 
    trait: 'beast_master', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#33691e', 
    description: '八納洞主，能呼風喚雨，驅使虎豹豺狼與巨象戰隊，陣前威風八面。', 
    appearanceYear: 184, 
    appearanceCity: 'banadong', 
    unitType: 'infantry' 
  },
  { 
    id: 'dailai', 
    name: '帶來洞主', 
    stats: { lead: 72, str: 76, int: 78, pol: 65, cha: 75 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#558b2f', 
    description: '祝融夫人之弟，八納洞與禿龍洞引路人，忠義勇烈。', 
    appearanceYear: 184, 
    appearanceCity: 'banadong', 
    unitType: 'infantry' 
  }
,
  // ================= 異域神國與塞外雄主 =================
  { 
    id: 'himiko', 
    name: '卑彌呼', 
    stats: { lead: 85, str: 50, int: 95, pol: 90, cha: 99 }, 
    trait: 'sorcery', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e91e63', 
    description: '東瀛邪馬台國女王，通鬼道惑眾，受魏帝曹叡冊封為「親魏倭王」，賜金印紫綬。', 
    appearanceYear: 184, 
    appearanceCity: 'yamatai', 
    unitType: 'archer' 
  },
  { 
    id: 'nashime', 
    name: '難升米', 
    stats: { lead: 80, str: 78, int: 84, pol: 86, cha: 82 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ad1457', 
    description: '邪馬台國正使兼大夫，奉女王之命出使曹魏，受封「率善中郎將」。', 
    appearanceYear: 184, 
    appearanceCity: 'yamatai', 
    unitType: 'infantry' 
  },
  { 
    id: 'huchuquan', 
    name: '呼廚泉', 
    stats: { lead: 82, str: 86, int: 60, pol: 65, cha: 78 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#5d4037', 
    description: '匈奴單于，羌渠單于之子，統領漠北控弦鐵騎，威震塞外。', 
    appearanceYear: 184, 
    appearanceCity: 'xiongnu', 
    unitType: 'cavalry' 
  },
  { 
    id: 'liu_bao', 
    name: '劉豹', 
    stats: { lead: 80, str: 84, int: 70, pol: 68, cha: 76 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#4e342e', 
    description: '匈奴左賢王，於夫羅之子，漢趙皇帝劉淵之父。', 
    appearanceYear: 190, 
    appearanceCity: 'xiongnu', 
    unitType: 'cavalry' 
  },
  { 
    id: 'tadun', 
    name: '蹋頓', 
    stats: { lead: 84, str: 90, int: 62, pol: 58, cha: 80 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#6d4c41', 
    description: '烏桓單于，驍勇善戰，人稱「總攬三郡，雄視幽冀」，白狼山大戰張遼。', 
    appearanceYear: 184, 
    appearanceCity: 'wuhuan', 
    unitType: 'cavalry' 
  },
  { 
    id: 'midang', 
    name: '迷當大王', 
    stats: { lead: 84, str: 88, int: 65, pol: 60, cha: 82 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#00897b', 
    description: '西羌國王，率鐵車重甲飛斧兵五萬助蜀伐魏，勇猛無比。', 
    appearanceYear: 184, 
    appearanceCity: 'xiqiang', 
    unitType: 'cavalry' 
  },
  { 
    id: 'ehe_shaoge', 
    name: '俄何燒戈', 
    stats: { lead: 78, str: 89, int: 50, pol: 40, cha: 70 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#00695c', 
    description: '西羌先鋒大將，使一柄沉重金背大刀，勇冠三軍。', 
    appearanceYear: 184, 
    appearanceCity: 'xiqiang', 
    unitType: 'cavalry' 
  },
  { 
    id: 'mulu', 
    name: '木鹿大王', 
    stats: { lead: 82, str: 85, int: 80, pol: 50, cha: 84 }, 
    trait: 'beast_master', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#33691e', 
    description: '八納洞主，能呼風喚雨，驅使虎豹豺狼與巨象戰隊，陣前威風八面。', 
    appearanceYear: 184, 
    appearanceCity: 'banadong', 
    unitType: 'infantry' 
  },
  { 
    id: 'dailai', 
    name: '帶來洞主', 
    stats: { lead: 72, str: 76, int: 78, pol: 65, cha: 75 }, 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#558b2f', 
    description: '祝融夫人之弟，八納洞與禿龍洞引路人，忠義勇烈。', 
    appearanceYear: 184, 
    appearanceCity: 'banadong', 
    unitType: 'infantry' 
  }
,
  // ================= 🧙‍♂️ 隱世仙真、槍神與特殊傳奇人物 =================
  { 
    id: 'nanhua_laoxian', 
    name: '南華老仙', 
    stats: { lead: 20, str: 20, int: 100, pol: 75, cha: 99 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#7e57c2', 
    description: '碧眼髯髯手杖藜之得道仙真，傳授張角《太平要術》三卷，雲遊四海，通曉天地玄機。', 
    appearanceYear: 184, 
    appearanceCity: 'ye', 
    unitType: 'archer' 
  },
  { 
    id: 'yu_ji', 
    name: '于吉仙人', 
    stats: { lead: 25, str: 15, int: 98, pol: 80, cha: 96 }, 
    trait: 'sorcery', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#26a69a', 
    description: '瑯琊宮道士，持《太平清領書》，以符水神藥普救江東百姓，威望極高。', 
    appearanceYear: 184, 
    appearanceCity: 'jianye', 
    unitType: 'infantry' 
  },
  { 
    id: 'guan_lu', 
    name: '管輅', 
    stats: { lead: 30, str: 20, int: 97, pol: 70, cha: 92 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#5c6bc0', 
    description: '字公明，三國第一神卜占星家，通曉《周易》仰觀天象，能精準推算生死吉凶與風雲變幻。', 
    appearanceYear: 194, 
    appearanceCity: 'luoyang', 
    unitType: 'archer' 
  },
  { 
    id: 'tong_yuan', 
    name: '童淵', 
    stats: { lead: 90, str: 99, int: 78, pol: 60, cha: 88 }, 
    trait: 'flying_gen', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#c62828', 
    description: '蓬萊散人、武學宗師，「百鳥朝鳳槍」創始人，趙雲、張任、張繡之授業恩師，天下槍術天花板！', 
    appearanceYear: 184, 
    appearanceCity: 'beiping', 
    unitType: 'cavalry' 
  },
  { 
    id: 'iyo', 
    name: '壹與', 
    stats: { lead: 75, str: 45, int: 92, pol: 88, cha: 96 }, 
    trait: 'sorcery', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ec407a', 
    description: '邪馬台國第二代巫女女王，卑彌呼之宗女，年十三撫定倭國大亂，續結親魏之盟。', 
    appearanceYear: 230, 
    appearanceCity: 'yamatai', 
    unitType: 'archer' 
  },
  { 
    id: 'shamoke', 
    name: '沙摩柯', 
    stats: { lead: 85, str: 93, int: 55, pol: 40, cha: 80 }, 
    trait: 'beast_master', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e65100', 
    description: '五溪蠻王，面如噀血，使一柄沉重鐵蒺藜骨朵，勇悍無比，陣前一箭射殺東吳猛將甘寧。', 
    appearanceYear: 207, 
    appearanceCity: 'wuling', 
    unitType: 'infantry' 
  }
,
  // ================= 🧙‍♂️ 隱世仙真、槍神與特殊傳奇人物 =================
  { 
    id: 'nanhua_laoxian', 
    name: '南華老仙', 
    stats: { lead: 20, str: 20, int: 100, pol: 75, cha: 99 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#7e57c2', 
    description: '碧眼髯髯手杖藜之得道仙真，傳授張角《太平要術》三卷，雲遊四海，通曉天地玄機。', 
    appearanceYear: 184, 
    appearanceCity: 'ye', 
    unitType: 'archer' 
  },
  { 
    id: 'yu_ji', 
    name: '于吉仙人', 
    stats: { lead: 25, str: 15, int: 98, pol: 80, cha: 96 }, 
    trait: 'sorcery', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#26a69a', 
    description: '瑯琊宮道士，持《太平清領書》，以符水神藥普救江東百姓，威望極高。', 
    appearanceYear: 184, 
    appearanceCity: 'jianye', 
    unitType: 'infantry' 
  },
  { 
    id: 'guan_lu', 
    name: '管輅', 
    stats: { lead: 30, str: 20, int: 97, pol: 70, cha: 92 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#5c6bc0', 
    description: '字公明，三國第一神卜占星家，通曉《周易》仰觀天象，能精準推算生死吉凶與風雲變幻。', 
    appearanceYear: 194, 
    appearanceCity: 'luoyang', 
    unitType: 'archer' 
  },
  { 
    id: 'tong_yuan', 
    name: '童淵', 
    stats: { lead: 90, str: 99, int: 78, pol: 60, cha: 88 }, 
    trait: 'flying_gen', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#c62828', 
    description: '蓬萊散人、武學宗師，「百鳥朝鳳槍」創始人，趙雲、張任、張繡之授業恩師，天下槍術天花板！', 
    appearanceYear: 184, 
    appearanceCity: 'beiping', 
    unitType: 'cavalry' 
  },
  { 
    id: 'iyo', 
    name: '壹與', 
    stats: { lead: 75, str: 45, int: 92, pol: 88, cha: 96 }, 
    trait: 'sorcery', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#ec407a', 
    description: '邪馬台國第二代巫女女王，卑彌呼之宗女，年十三撫定倭國大亂，續結親魏之盟。', 
    appearanceYear: 230, 
    appearanceCity: 'yamatai', 
    unitType: 'archer' 
  },
  { 
    id: 'shamoke', 
    name: '沙摩柯', 
    stats: { lead: 85, str: 93, int: 55, pol: 40, cha: 80 }, 
    trait: 'beast_master', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#e65100', 
    description: '五溪蠻王，面如噀血，使一柄沉重鐵蒺藜骨朵，勇悍無比，陣前一箭射殺東吳猛將甘寧。', 
    appearanceYear: 207, 
    appearanceCity: 'wuling', 
    unitType: 'infantry' 
  },

  // ================= 🌀 異時空穿越名將與跨時代英傑 =================
  { 
    id: 'xiang_yu', 
    name: '項羽', 
    stats: { lead: 98, str: 100, int: 69, pol: 45, cha: 95 }, 
    trait: 'flying_gen', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#b71c1c', 
    description: '西楚霸王，羽之神勇千古無二。力拔山兮氣蓋世，烏江時空逆流穿越至三國！', 
    appearanceYear: 184, 
    appearanceCity: 'moling', 
    unitType: 'cavalry' 
  },
  { 
    id: 'huo_qubing', 
    name: '霍去病', 
    stats: { lead: 97, str: 96, int: 78, pol: 50, cha: 94 }, 
    trait: 'flying_gen', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#c2185b', 
    description: '大漢冠軍侯、大司馬驃騎將軍。封狼居胥，六擊匈奴，千里奔襲如入無人之境！', 
    appearanceYear: 184, 
    appearanceCity: 'shanyu_ting', 
    unitType: 'cavalry' 
  },
  { 
    id: 'bai_qi', 
    name: '白起', 
    stats: { lead: 100, str: 91, int: 95, pol: 60, cha: 70 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#4a148c', 
    description: '大秦武安君、戰國殺神。長平滅趙，一生料敵如神，百戰百勝！', 
    appearanceYear: 184, 
    appearanceCity: 'changan', 
    unitType: 'infantry' 
  },
  { 
    id: 'li_bai', 
    name: '李白', 
    stats: { lead: 60, str: 85, int: 96, pol: 72, cha: 100 }, 
    trait: 'virtue', 
    portrait: 'portraits/default.jpg', 
    portraitColor: '#00838f', 
    description: '盛唐詩仙青蓮居士。仗劍去國，辭親遠遊，十步殺一人，千里不留行！', 
    appearanceYear: 184, 
    appearanceCity: 'luoyang', 
    unitType: 'cavalry' 
  },
  { 
    id: 'chu_tianxing', 
    name: '楚天行', 
    stats: { lead: 82, str: 75, int: 99, pol: 95, cha: 88 }, 
    trait: 'divine_calc', 
    portrait: 'portraits/custom_lord_1.jpg', 
    portraitColor: '#00695c', 
    description: '現代穿越軍工歷史學家。攜帶高爐煉鋼、野戰外科與現代兵棋推演知識橫空降世！', 
    appearanceYear: 184, 
    appearanceCity: 'xuchang', 
    unitType: 'archer' 
  }

];


