// 三國志地圖策略遊戲 - 地圖與勢力數據 (map-data.js)

export const FACTIONS = {
  cao_cao: {
    id: 'cao_cao',
    name: '曹操',
    color: '#1565c0', // 藍色
    secondaryColor: 'rgba(21, 101, 192, 0.2)',
    banner: '曹',
    leader: '曹操',
    trait: 'agriculture' // 屯田：糧草收入與初始糧草多
  },
  liu_bei: {
    id: 'liu_bei',
    name: '劉備',
    color: '#2e7d32', // 綠色
    secondaryColor: 'rgba(46, 125, 50, 0.2)',
    banner: '劉',
    leader: '劉備',
    trait: 'virtue' // 仁德：士氣自然恢復，登用率高
  },
  sun_quan: {
    id: 'sun_quan',
    name: '孫權',
    color: '#c62828', // 紅色
    secondaryColor: 'rgba(198, 40, 40, 0.2)',
    banner: '孫',
    leader: '孫權',
    trait: 'commerce' // 商業：黃金收入多，初始黃金多
  },
  dong_zhuo: {
    id: 'dong_zhuo',
    name: '董卓',
    color: '#6a1b9a', // 紫色
    secondaryColor: 'rgba(106, 27, 154, 0.2)',
    banner: '董',
    leader: '董卓',
    trait: 'tyranny' // 暴政：徵兵多但掉士氣
  },
  yuan_shao: {
    id: 'yuan_shao',
    name: '袁紹',
    color: '#fdd835', // 黃色
    secondaryColor: 'rgba(253, 216, 53, 0.2)',
    banner: '袁',
    leader: '袁紹',
    trait: 'prestige' // 名門：初始兵力與資源較多
  },
  zhang_jiao: {
    id: 'zhang_jiao',
    name: '張角',
    color: '#ffb300', // 橘黃色
    secondaryColor: 'rgba(255, 179, 0, 0.2)',
    banner: '黃',
    leader: '張角',
    trait: 'horde' // 黃天：極大量初始兵力，但農商極低
  },
  liu_biao: {
    id: 'liu_biao',
    name: '劉表',
    color: '#00acc1', // 青色
    secondaryColor: 'rgba(0, 172, 193, 0.2)',
    banner: '劉',
    leader: '劉表',
    trait: 'defensive' // 防守：守城時士氣不易掉
  },
  ma_teng: {
    id: 'ma_teng',
    name: '馬騰',
    color: '#8d6e63', // 棕色
    secondaryColor: 'rgba(141, 110, 99, 0.2)',
    banner: '馬',
    leader: '馬騰',
    trait: 'cavalry_master' // 西涼：騎兵攻擊力增加
  },
  yuan_shu: {
    id: 'yuan_shu',
    name: '袁術',
    color: '#f48fb1', // 粉色
    secondaryColor: 'rgba(244, 143, 177, 0.2)',
    banner: '袁',
    leader: '袁術',
    trait: 'prestige'
  },
  gongsun_zan: {
    id: 'gongsun_zan',
    name: '公孫瓚',
    color: '#9e9e9e', // 亮灰
    secondaryColor: 'rgba(158, 158, 158, 0.2)',
    banner: '公孫',
    leader: '公孫瓚',
    trait: 'cavalry_master'
  },
  lu_bu: {
    id: 'lu_bu',
    name: '呂布',
    color: '#d50000', // 赤紅
    secondaryColor: 'rgba(213, 0, 0, 0.2)',
    banner: '呂',
    leader: '呂布',
    trait: 'flying_gen' // 飛將：突擊破陣
  },
  himiko: {
    id: 'himiko',
    name: '邪馬台・卑彌呼',
    color: '#e91e63', // 櫻花粉紅
    secondaryColor: 'rgba(233, 30, 99, 0.2)',
    banner: '倭',
    leader: '卑彌呼',
    trait: 'sorcery' // 鬼道：巫祝幻術，防守戰力極高
  },
  xiongnu: {
    id: 'xiongnu',
    name: '匈奴・呼廚泉',
    color: '#5d4037', // 漠北深褐
    secondaryColor: 'rgba(93, 64, 55, 0.2)',
    banner: '胡',
    leader: '呼廚泉',
    trait: 'horde' // 控弦之士：騎兵極度強悍
  },
  midang: {
    id: 'midang',
    name: '西羌・迷當',
    color: '#00897b', // 青海綠
    secondaryColor: 'rgba(0, 137, 123, 0.2)',
    banner: '羌',
    leader: '迷當大王',
    trait: 'cavalry_master' // 羌騎：重甲飛斧
  },
  mulu: {
    id: 'mulu',
    name: '八納洞・木鹿',
    color: '#33691e', // 雨林濃綠
    secondaryColor: 'rgba(51, 105, 30, 0.2)',
    banner: '蠻',
    leader: '木鹿大王',
    trait: 'beast_master' // 戰象：巨象破陣
  },
  neutral: {
    id: 'neutral',
    name: '在野/中立',
    color: '#757575', // 灰色
    secondaryColor: 'rgba(117, 117, 117, 0.2)',
    banner: '空',
    leader: '無'
  }
};

export const CITIES = [
  // ================= 塞外漠北與東北異域 =================
  {
    id: 'xiongnu',
    name: '單于庭',
    regionTag: '漠北大漠・匈奴王庭',
    x: 460,
    y: 50,
    faction: 'neutral',
    agriculture: 150,
    commerce: 280,
    defense: 500,
    troops: 25000,
    morale: 88,
    gold: 5000,
    food: 20000,
    maxAgriculture: 600,
    maxCommerce: 900,
    maxDefense: 1000
  },
  {
    id: 'wuhuan',
    name: '白狼山',
    regionTag: '遼西塞外・烏桓汗國',
    x: 740,
    y: 50,
    faction: 'neutral',
    agriculture: 180,
    commerce: 240,
    defense: 550,
    troops: 20000,
    morale: 85,
    gold: 4000,
    food: 16000,
    maxAgriculture: 700,
    maxCommerce: 800,
    maxDefense: 1000
  },
  {
    id: 'samhan',
    name: '三韓帶方',
    regionTag: '朝鮮半島・三韓故地',
    x: 950,
    y: 130,
    faction: 'neutral',
    agriculture: 300,
    commerce: 380,
    defense: 500,
    troops: 16000,
    morale: 80,
    gold: 5500,
    food: 18000,
    maxAgriculture: 900,
    maxCommerce: 1000,
    maxDefense: 1000
  },
  {
    id: 'liaodong',
    name: '遼東',
    regionTag: '塞外要塞・襄平',
    x: 880,
    y: 80,
    faction: 'neutral',
    agriculture: 250,
    commerce: 260,
    defense: 600,
    troops: 18000,
    morale: 80,
    gold: 4500,
    food: 16000,
    maxAgriculture: 850,
    maxCommerce: 850,
    maxDefense: 1100
  },
  {
    id: 'beiping',
    name: '北平',
    regionTag: '幽州重鎮・白馬義從',
    x: 790,
    y: 120,
    faction: 'yuan_shao',
    agriculture: 240,
    commerce: 220,
    defense: 350,
    troops: 16000,
    morale: 75,
    gold: 3500,
    food: 14000,
    maxAgriculture: 850,
    maxCommerce: 850,
    maxDefense: 1000
  },
  {
    id: 'jinyang',
    name: '晉陽',
    regionTag: '并州狼騎・太原',
    x: 570,
    y: 170,
    faction: 'neutral',
    agriculture: 280,
    commerce: 240,
    defense: 650,
    troops: 20000,
    morale: 85,
    gold: 4000,
    food: 18000,
    maxAgriculture: 900,
    maxCommerce: 850,
    maxDefense: 1200
  },
  {
    id: 'ye',
    name: '鄴',
    regionTag: '河北霸府・銅雀臺',
    x: 690,
    y: 220,
    faction: 'yuan_shao',
    agriculture: 380,
    commerce: 400,
    defense: 550,
    troops: 28000,
    morale: 82,
    gold: 5500,
    food: 22000,
    maxAgriculture: 1000,
    maxCommerce: 1000,
    maxDefense: 1200
  },

  // ================= 西域絲路與西羌異域 =================
  {
    id: 'dayuan',
    name: '汗血宛國',
    regionTag: '西域絲路・大宛汗國',
    x: 45,
    y: 210,
    faction: 'neutral',
    agriculture: 200,
    commerce: 600,
    defense: 450,
    troops: 15000,
    morale: 85,
    gold: 8000,
    food: 12000,
    maxAgriculture: 700,
    maxCommerce: 1400,
    maxDefense: 900
  },
  {
    id: 'dunhuang',
    name: '敦煌',
    regionTag: '絲路咽喉・陽關玉門',
    x: 160,
    y: 260,
    faction: 'neutral',
    agriculture: 180,
    commerce: 500,
    defense: 500,
    troops: 12000,
    morale: 78,
    gold: 6500,
    food: 10000,
    maxAgriculture: 750,
    maxCommerce: 1300,
    maxDefense: 1000
  },
  {
    id: 'xiqiang',
    name: '積石西羌',
    regionTag: '青藏雪域・西羌王國',
    x: 110,
    y: 430,
    faction: 'neutral',
    agriculture: 200,
    commerce: 250,
    defense: 700,
    troops: 22000,
    morale: 88,
    gold: 4500,
    food: 18000,
    maxAgriculture: 750,
    maxCommerce: 800,
    maxDefense: 1200
  },
  {
    id: 'tianshui',
    name: '天水',
    regionTag: '西涼門戶・隴西要衝',
    x: 290,
    y: 320,
    faction: 'dong_zhuo',
    agriculture: 200,
    commerce: 180,
    defense: 450,
    troops: 20000,
    morale: 78,
    gold: 3500,
    food: 12000,
    maxAgriculture: 750,
    maxCommerce: 700,
    maxDefense: 1000
  },
  {
    id: 'changan',
    name: '長安',
    regionTag: '西京故都・關中雄風',
    x: 420,
    y: 340,
    faction: 'dong_zhuo',
    agriculture: 420,
    commerce: 440,
    defense: 850,
    troops: 38000,
    morale: 88,
    gold: 8500,
    food: 32000,
    maxAgriculture: 1200,
    maxCommerce: 1200,
    maxDefense: 1500
  },

  // ================= 中原腹地 =================
  {
    id: 'luoyang',
    name: '洛陽',
    regionTag: '東漢帝都・天下中樞',
    x: 540,
    y: 330,
    faction: 'neutral',
    agriculture: 200,
    commerce: 220,
    defense: 400,
    troops: 10000,
    morale: 60,
    gold: 2500,
    food: 8000,
    maxAgriculture: 1500,
    maxCommerce: 1500,
    maxDefense: 1500
  },
  {
    id: 'xuchang',
    name: '許昌',
    regionTag: '魏武皇都・屯田根本',
    x: 630,
    y: 360,
    faction: 'cao_cao',
    agriculture: 480,
    commerce: 500,
    defense: 650,
    troops: 32000,
    morale: 92,
    gold: 6500,
    food: 28000,
    maxAgriculture: 1100,
    maxCommerce: 1100,
    maxDefense: 1200
  },
  {
    id: 'runan',
    name: '汝南',
    regionTag: '淮汝名邦・人傑地靈',
    x: 690,
    y: 420,
    faction: 'cao_cao',
    agriculture: 300,
    commerce: 280,
    defense: 420,
    troops: 14000,
    morale: 78,
    gold: 3200,
    food: 12000,
    maxAgriculture: 850,
    maxCommerce: 850,
    maxDefense: 950
  },
  {
    id: 'shouchun',
    name: '壽春',
    regionTag: '淮南要津・合肥門戶',
    x: 770,
    y: 430,
    faction: 'neutral',
    agriculture: 260,
    commerce: 320,
    defense: 380,
    troops: 12000,
    morale: 65,
    gold: 2500,
    food: 10000,
    maxAgriculture: 950,
    maxCommerce: 1000,
    maxDefense: 950
  },

  // ================= 西南巴蜀與極南異域 =================
  {
    id: 'hanzhong',
    name: '漢中',
    regionTag: '蜀門鎖鑰・天險要衝',
    x: 390,
    y: 460,
    faction: 'neutral',
    agriculture: 270,
    commerce: 220,
    defense: 650,
    troops: 14000,
    morale: 70,
    gold: 2800,
    food: 16000,
    maxAgriculture: 950,
    maxCommerce: 850,
    maxDefense: 1150
  },
  {
    id: 'chengdu',
    name: '成都',
    regionTag: '天府之國・錦官皇城',
    x: 270,
    y: 530,
    faction: 'liu_bei',
    agriculture: 520,
    commerce: 420,
    defense: 750,
    troops: 28000,
    morale: 90,
    gold: 5500,
    food: 32000,
    maxAgriculture: 1300,
    maxCommerce: 1100,
    maxDefense: 1300
  },
  {
    id: 'yunnan',
    name: '雲南',
    regionTag: '南蠻故地・建寧滇池',
    x: 170,
    y: 620,
    faction: 'neutral',
    agriculture: 240,
    commerce: 200,
    defense: 550,
    troops: 18000,
    morale: 88,
    gold: 4000,
    food: 16000,
    maxAgriculture: 950,
    maxCommerce: 850,
    maxDefense: 1050
  },
  {
    id: 'banadong',
    name: '八納洞',
    regionTag: '極南蠻荒・木鹿象兵',
    x: 75,
    y: 670,
    faction: 'neutral',
    agriculture: 180,
    commerce: 220,
    defense: 600,
    troops: 20000,
    morale: 92,
    gold: 4500,
    food: 15000,
    maxAgriculture: 800,
    maxCommerce: 800,
    maxDefense: 1100
  },

  // ================= 荊襄與江淮 =================
  {
    id: 'xiangyang',
    name: '襄陽',
    regionTag: '九省通衢・水陸要塞',
    x: 560,
    y: 450,
    faction: 'liu_bei',
    agriculture: 400,
    commerce: 400,
    defense: 550,
    troops: 18000,
    morale: 82,
    gold: 4500,
    food: 20000,
    maxAgriculture: 1050,
    maxCommerce: 1050,
    maxDefense: 1050
  },
  {
    id: 'chaisang',
    name: '柴桑',
    regionTag: '長江水砦・周郎點將',
    x: 720,
    y: 510,
    faction: 'neutral',
    agriculture: 320,
    commerce: 380,
    defense: 600,
    troops: 22000,
    morale: 88,
    gold: 5000,
    food: 20000,
    maxAgriculture: 1050,
    maxCommerce: 1150,
    maxDefense: 1150
  },
  {
    id: 'wuling',
    name: '武陵',
    regionTag: '荊南四郡・世外桃源',
    x: 470,
    y: 570,
    faction: 'neutral',
    agriculture: 220,
    commerce: 200,
    defense: 320,
    troops: 8000,
    morale: 60,
    gold: 1800,
    food: 8000,
    maxAgriculture: 850,
    maxCommerce: 750,
    maxDefense: 850
  },
  {
    id: 'changsha',
    name: '長沙',
    regionTag: '楚漢名城・黃忠故里',
    x: 580,
    y: 560,
    faction: 'neutral',
    agriculture: 300,
    commerce: 270,
    defense: 480,
    troops: 13000,
    morale: 75,
    gold: 3200,
    food: 14000,
    maxAgriculture: 1000,
    maxCommerce: 950,
    maxDefense: 1050
  },
  {
    id: 'jiaozhi',
    name: '交趾',
    regionTag: '嶺南珠香・南海重鎮',
    x: 370,
    y: 650,
    faction: 'neutral',
    agriculture: 340,
    commerce: 380,
    defense: 450,
    troops: 14000,
    morale: 78,
    gold: 5500,
    food: 20000,
    maxAgriculture: 1050,
    maxCommerce: 1150,
    maxDefense: 950
  },

  // ================= 江東與東瀛異域、台灣 =================
  {
    id: 'jianye',
    name: '建業',
    regionTag: '六朝古都・東吳帝京',
    x: 850,
    y: 460,
    faction: 'sun_quan',
    agriculture: 420,
    commerce: 580,
    defense: 650,
    troops: 30000,
    morale: 94,
    gold: 7500,
    food: 26000,
    maxAgriculture: 1150,
    maxCommerce: 1450,
    maxDefense: 1250
  },
  {
    id: 'huiji',
    name: '會稽',
    regionTag: '越水要衝・山越重地',
    x: 870,
    y: 550,
    faction: 'sun_quan',
    agriculture: 320,
    commerce: 340,
    defense: 420,
    troops: 16000,
    morale: 82,
    gold: 3800,
    food: 15000,
    maxAgriculture: 950,
    maxCommerce: 950,
    maxDefense: 950
  },
  {
    id: 'yizhou',
    name: '夷州',
    regionTag: '海東神島・台灣',
    x: 935,
    y: 645,
    faction: 'neutral',
    agriculture: 300,
    commerce: 350,
    defense: 300,
    troops: 8000,
    morale: 80,
    gold: 4500,
    food: 14000,
    maxAgriculture: 1050,
    maxCommerce: 1150,
    maxDefense: 850
  },
  {
    id: 'yamatai',
    name: '邪馬台',
    regionTag: '東瀛倭國・卑彌呼女王',
    x: 965,
    y: 360,
    faction: 'neutral',
    agriculture: 350,
    commerce: 480,
    defense: 600,
    troops: 24000,
    morale: 95,
    gold: 8800,
    food: 25000,
    maxAgriculture: 1100,
    maxCommerce: 1300,
    maxDefense: 1200
  }
];

export const CONNECTIONS = [
  // 漠北塞外與東北異域通道
  ['xiongnu', 'jinyang'],
  ['xiongnu', 'dunhuang'],
  ['xiongnu', 'wuhuan'],
  ['wuhuan', 'beiping'],
  ['wuhuan', 'liaodong'],
  ['beiping', 'liaodong'],
  ['liaodong', 'samhan'],
  ['beiping', 'ye'],
  ['beiping', 'jinyang'],
  ['jinyang', 'ye'],
  ['jinyang', 'luoyang'],

  // 中原通道
  ['ye', 'luoyang'],
  ['ye', 'xuchang'],
  ['ye', 'shouchun'],
  ['luoyang', 'changan'],
  ['luoyang', 'xuchang'],
  ['xuchang', 'runan'],
  ['runan', 'shouchun'],
  ['shouchun', 'jianye'],
  ['shouchun', 'chaisang'],

  // 西域絲路與西北通道
  ['dayuan', 'dunhuang'],
  ['dayuan', 'xiqiang'],
  ['dunhuang', 'tianshui'],
  ['xiqiang', 'dunhuang'],
  ['xiqiang', 'tianshui'],
  ['xiqiang', 'chengdu'],
  ['changan', 'tianshui'],
  ['changan', 'hanzhong'],

  // 巴蜀與西南、極南異域通道
  ['hanzhong', 'chengdu'],
  ['hanzhong', 'xiangyang'],
  ['chengdu', 'wuling'],
  ['chengdu', 'yunnan'],
  ['yunnan', 'banadong'],
  ['banadong', 'jiaozhi'],
  ['yunnan', 'jiaozhi'],

  // 荊襄與嶺南通道
  ['xiangyang', 'xuchang'],
  ['xiangyang', 'runan'],
  ['xiangyang', 'chaisang'],
  ['xiangyang', 'changsha'],
  ['chaisang', 'jianye'],
  ['chaisang', 'huiji'],
  ['chaisang', 'changsha'],
  ['changsha', 'wuling'],
  ['changsha', 'jiaozhi'],
  ['wuling', 'jiaozhi'],

  // 江東與夷州 (台灣)、東瀛 (邪馬台)、三韓海上通道
  ['jianye', 'huiji'],
  ['huiji', 'yizhou'],
  ['jianye', 'yizhou'],
  ['huiji', 'yamatai'],
  ['jianye', 'yamatai'],
  ['samhan', 'yamatai'],
  ['yizhou', 'yamatai']
];
